# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/t-ptostado/Project/repos/LinuxTracepoints

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/t-ptostado/Project/repos/LinuxTracepoints

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/t-ptostado/Project/repos/LinuxTracepoints/CMakeFiles /home/t-ptostado/Project/repos/LinuxTracepoints//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/t-ptostado/Project/repos/LinuxTracepoints/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tracepoint

# Build rule for target.
tracepoint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tracepoint
.PHONY : tracepoint

# fast build rule for target.
tracepoint/fast:
	$(MAKE) $(MAKESILENT) -f libtracepoint/src/CMakeFiles/tracepoint.dir/build.make libtracepoint/src/CMakeFiles/tracepoint.dir/build
.PHONY : tracepoint/fast

#=============================================================================
# Target rules for targets named tpp-utest

# Build rule for target.
tpp-utest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tpp-utest
.PHONY : tpp-utest

# fast build rule for target.
tpp-utest/fast:
	$(MAKE) $(MAKESILENT) -f libtracepoint/utest/CMakeFiles/tpp-utest.dir/build.make libtracepoint/utest/CMakeFiles/tpp-utest.dir/build
.PHONY : tpp-utest/fast

#=============================================================================
# Target rules for targets named tracepoint-utest

# Build rule for target.
tracepoint-utest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tracepoint-utest
.PHONY : tracepoint-utest

# fast build rule for target.
tracepoint-utest/fast:
	$(MAKE) $(MAKESILENT) -f libtracepoint/utest/CMakeFiles/tracepoint-utest.dir/build.make libtracepoint/utest/CMakeFiles/tracepoint-utest.dir/build
.PHONY : tracepoint-utest/fast

#=============================================================================
# Target rules for targets named tpp-sample

# Build rule for target.
tpp-sample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tpp-sample
.PHONY : tpp-sample

# fast build rule for target.
tpp-sample/fast:
	$(MAKE) $(MAKESILENT) -f libtracepoint/samples/CMakeFiles/tpp-sample.dir/build.make libtracepoint/samples/CMakeFiles/tpp-sample.dir/build
.PHONY : tpp-sample/fast

#=============================================================================
# Target rules for targets named tracepoint-sample

# Build rule for target.
tracepoint-sample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tracepoint-sample
.PHONY : tracepoint-sample

# fast build rule for target.
tracepoint-sample/fast:
	$(MAKE) $(MAKESILENT) -f libtracepoint/samples/CMakeFiles/tracepoint-sample.dir/build.make libtracepoint/samples/CMakeFiles/tracepoint-sample.dir/build
.PHONY : tracepoint-sample/fast

#=============================================================================
# Target rules for targets named tracepoint-decode

# Build rule for target.
tracepoint-decode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tracepoint-decode
.PHONY : tracepoint-decode

# fast build rule for target.
tracepoint-decode/fast:
	$(MAKE) $(MAKESILENT) -f libtracepoint-decode-cpp/src/CMakeFiles/tracepoint-decode.dir/build.make libtracepoint-decode-cpp/src/CMakeFiles/tracepoint-decode.dir/build
.PHONY : tracepoint-decode/fast

#=============================================================================
# Target rules for targets named eventheader-tracepoint

# Build rule for target.
eventheader-tracepoint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eventheader-tracepoint
.PHONY : eventheader-tracepoint

# fast build rule for target.
eventheader-tracepoint/fast:
	$(MAKE) $(MAKESILENT) -f libeventheader-tracepoint/src/CMakeFiles/eventheader-tracepoint.dir/build.make libeventheader-tracepoint/src/CMakeFiles/eventheader-tracepoint.dir/build
.PHONY : eventheader-tracepoint/fast

#=============================================================================
# Target rules for targets named eventheader-interceptor-sample

# Build rule for target.
eventheader-interceptor-sample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eventheader-interceptor-sample
.PHONY : eventheader-interceptor-sample

# fast build rule for target.
eventheader-interceptor-sample/fast:
	$(MAKE) $(MAKESILENT) -f libeventheader-tracepoint/samples/CMakeFiles/eventheader-interceptor-sample.dir/build.make libeventheader-tracepoint/samples/CMakeFiles/eventheader-interceptor-sample.dir/build
.PHONY : eventheader-interceptor-sample/fast

#=============================================================================
# Target rules for targets named eventheader-sample

# Build rule for target.
eventheader-sample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eventheader-sample
.PHONY : eventheader-sample

# fast build rule for target.
eventheader-sample/fast:
	$(MAKE) $(MAKESILENT) -f libeventheader-tracepoint/samples/CMakeFiles/eventheader-sample.dir/build.make libeventheader-tracepoint/samples/CMakeFiles/eventheader-sample.dir/build
.PHONY : eventheader-sample/fast

#=============================================================================
# Target rules for targets named dynamic-sample

# Build rule for target.
dynamic-sample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dynamic-sample
.PHONY : dynamic-sample

# fast build rule for target.
dynamic-sample/fast:
	$(MAKE) $(MAKESILENT) -f libeventheader-tracepoint/samples/CMakeFiles/dynamic-sample.dir/build.make libeventheader-tracepoint/samples/CMakeFiles/dynamic-sample.dir/build
.PHONY : dynamic-sample/fast

#=============================================================================
# Target rules for targets named eventheader-register

# Build rule for target.
eventheader-register: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eventheader-register
.PHONY : eventheader-register

# fast build rule for target.
eventheader-register/fast:
	$(MAKE) $(MAKESILENT) -f libeventheader-tracepoint/tools/CMakeFiles/eventheader-register.dir/build.make libeventheader-tracepoint/tools/CMakeFiles/eventheader-register.dir/build
.PHONY : eventheader-register/fast

#=============================================================================
# Target rules for targets named eventheader-decode

# Build rule for target.
eventheader-decode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eventheader-decode
.PHONY : eventheader-decode

# fast build rule for target.
eventheader-decode/fast:
	$(MAKE) $(MAKESILENT) -f libeventheader-decode-cpp/src/CMakeFiles/eventheader-decode.dir/build.make libeventheader-decode-cpp/src/CMakeFiles/eventheader-decode.dir/build
.PHONY : eventheader-decode/fast

#=============================================================================
# Target rules for targets named eventheader-decode-file

# Build rule for target.
eventheader-decode-file: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eventheader-decode-file
.PHONY : eventheader-decode-file

# fast build rule for target.
eventheader-decode-file/fast:
	$(MAKE) $(MAKESILENT) -f libeventheader-decode-cpp/samples/CMakeFiles/eventheader-decode-file.dir/build.make libeventheader-decode-cpp/samples/CMakeFiles/eventheader-decode-file.dir/build
.PHONY : eventheader-decode-file/fast

#=============================================================================
# Target rules for targets named decode-perf

# Build rule for target.
decode-perf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 decode-perf
.PHONY : decode-perf

# fast build rule for target.
decode-perf/fast:
	$(MAKE) $(MAKESILENT) -f libeventheader-decode-cpp/tools/CMakeFiles/decode-perf.dir/build.make libeventheader-decode-cpp/tools/CMakeFiles/decode-perf.dir/build
.PHONY : decode-perf/fast

#=============================================================================
# Target rules for targets named tracepoint-control

# Build rule for target.
tracepoint-control: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tracepoint-control
.PHONY : tracepoint-control

# fast build rule for target.
tracepoint-control/fast:
	$(MAKE) $(MAKESILENT) -f libtracepoint-control-cpp/src/CMakeFiles/tracepoint-control.dir/build.make libtracepoint-control-cpp/src/CMakeFiles/tracepoint-control.dir/build
.PHONY : tracepoint-control/fast

#=============================================================================
# Target rules for targets named control-session

# Build rule for target.
control-session: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 control-session
.PHONY : control-session

# fast build rule for target.
control-session/fast:
	$(MAKE) $(MAKESILENT) -f libtracepoint-control-cpp/samples/CMakeFiles/control-session.dir/build.make libtracepoint-control-cpp/samples/CMakeFiles/control-session.dir/build
.PHONY : control-session/fast

#=============================================================================
# Target rules for targets named control-lookup

# Build rule for target.
control-lookup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 control-lookup
.PHONY : control-lookup

# fast build rule for target.
control-lookup/fast:
	$(MAKE) $(MAKESILENT) -f libtracepoint-control-cpp/samples/CMakeFiles/control-lookup.dir/build.make libtracepoint-control-cpp/samples/CMakeFiles/control-lookup.dir/build
.PHONY : control-lookup/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... control-lookup"
	@echo "... control-session"
	@echo "... decode-perf"
	@echo "... dynamic-sample"
	@echo "... eventheader-decode"
	@echo "... eventheader-decode-file"
	@echo "... eventheader-interceptor-sample"
	@echo "... eventheader-register"
	@echo "... eventheader-sample"
	@echo "... eventheader-tracepoint"
	@echo "... tpp-sample"
	@echo "... tpp-utest"
	@echo "... tracepoint"
	@echo "... tracepoint-control"
	@echo "... tracepoint-decode"
	@echo "... tracepoint-sample"
	@echo "... tracepoint-utest"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

